# E-Commerce Sales Analysis

## Project Overview

This project analyzes an e-commerce dataset containing customer transactions, products, sales, and geographical information.

The objective is to clean the data, perform business analysis using PostgreSQL, and visualize important insights using Python libraries such as Matplotlib and Seaborn.

## Tools Used

- Python (Pandas)
- PostgreSQL
- SQLAlchemy
- Matplotlib
- Seaborn

## Business Goals

The analysis focuses on:

- Revenue performance
- Customer behavior
- Product performance
- Sales trends
- Customer segmentation
- Market analysis

In [1]:
import pandas as pd

In [2]:
# importing the e commerce.csv data into pandas and making a copy for analysis
df_org = pd.read_csv('Ecommerce_Data/ecommerce_data.csv', encoding= "latin-1")
df = df_org.copy()
sample_df = df_org.sample(1000)

sample_df.to_csv(
    "sample_ecommerce.csv",
    index=False
)

# 1. Data Cleaning

The raw dataset contained:

- Missing customer IDs
- Missing product descriptions
- Duplicate transactions
- Invalid quantities
- Invalid unit prices

Cleaning steps performed:

- Removed duplicate rows
- Removed transactions with negative quantity
- Removed transactions with zero or negative prices
- Removed rows without customer ID
- Created revenue column
- Converted date columns into usable format

In [3]:
#checking if the data is loaded sucessfully and showing the first 5 data 
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [4]:
# checking the info of the dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [5]:
# checking the rows and colums(shape) of the dataframe
df.shape

(541909, 8)

In [6]:
#checking if there are any null values in the dataframe
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [7]:
#filling the description column with no information
df["Description"] = df["Description"].fillna("No information")
df["Description"].isnull().sum()

np.int64(0)

In [8]:
# dropping the customer id null rows because we cannot create fake customers by filling it with median
df= df.dropna(subset= ["CustomerID"])
df["CustomerID"].isnull().sum()

np.int64(0)

In [9]:
# changing the type of customerID from float to integer
df["CustomerID"] = df["CustomerID"].astype("int64")
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680,France

In [10]:
#checking the updated dataframe null values
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [11]:
df.shape

(406829, 8)

In [12]:
#checking the duplicates in the dataframe
df.duplicated().sum()

np.int64(5225)

In [13]:
# dropping the duplicates
df =df.drop_duplicates()

In [14]:
df.shape

(401604, 8)

In [15]:
#checking the unqiue values in invoice no
df["InvoiceNo"].nunique()

22190

In [16]:
# checking the unique customers 
df["CustomerID"].nunique()

4372

In [17]:
# transforming invoicedate into datetime format
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], format="%m/%d/%Y %H:%M")

#make separate column for month_year and time
df["Invoice_Day_Month_Year"] = df["InvoiceDate"].dt.strftime("%d/%m/%Y")
df["Invoice_Time"] = df["InvoiceDate"].dt.strftime("%H:%M")

In [18]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Invoice_Day_Month_Year,Invoice_Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,01/12/2010,08:26
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,01/12/2010,08:26
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,01/12/2010,08:26
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,01/12/2010,08:26
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,01/12/2010,08:26

In [19]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Invoice_Day_Month_Year,Invoice_Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,01/12/2010,08:26
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,01/12/2010,08:26
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,01/12/2010,08:26
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,01/12/2010,08:26
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,01/12/2010,08:26

In [20]:
#dropping colum Invoice date after separating year_month and time
df.drop(columns="InvoiceDate", inplace=True)

In [21]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Invoice_Day_Month_Year,Invoice_Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850,United Kingdom,01/12/2010,08:26
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850,United Kingdom,01/12/2010,08:26
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850,United Kingdom,01/12/2010,08:26
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850,United Kingdom,01/12/2010,08:26
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850,United Kingdom,01/12/2010,08:26

In [22]:
#checking the statistics summary in quantity
df["Quantity"].describe()

count    401604.000000
mean         12.183273
std         250.283037
min      -80995.000000
25%           2.000000
50%           5.000000
75%          12.000000
max       80995.000000
Name: Quantity, dtype: float64

In [23]:
# checking the values less than 0 in quantity
df[df["Quantity"]<0]

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Invoice_Day_Month_Year,Invoice_Time
141,C536379,D,Discount,-1,27.50,14527,United Kingdom,01/12/2010,09:41
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,4.65,15311,United Kingdom,01/12/2010,09:49
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,1.65,17548,United Kingdom,01/12/2010,10:24
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,0.29,17548,United Kingdom,01/12/2010,10:24
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,0.29,17548,United Kingdom,01/12/2010,10:24
...,...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,0.83,14397,United Kingdom,09/12/2011,09:57
541541,C581499,M,Manual,-1,224.69,15498,United Kingdom,09/12/2011,10:28
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,10.95,15311,United Kingdom,09/12/2011,11:57
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,1.25,17315,United Kingdom,09/12/2011,11:58
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,1.25,17315,United Kingdom,09/12/2011,11:58

In [24]:
# removing all the negative values in quantity
df = df[df["Quantity"]>0]

In [25]:
# checking the statistics summaray in unit price
df["UnitPrice"].describe()

count    392732.000000
mean          3.125596
std          22.240725
min           0.000000
25%           1.250000
50%           1.950000
75%           3.750000
max        8142.750000
Name: UnitPrice, dtype: float64

In [26]:
#checking if the values is less than or equals to  0 in unitprice
df[df["UnitPrice"]<= 0]

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Invoice_Day_Month_Year,Invoice_Time
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,0.0,12647,Germany,05/12/2010,14:02
33576,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,0.0,16560,United Kingdom,16/12/2010,14:36
40089,539722,22423,REGENCY CAKESTAND 3 TIER,10,0.0,14911,EIRE,21/12/2010,13:45
47068,540372,22090,PAPER BUNTING RETROSPOT,24,0.0,13081,United Kingdom,06/01/2011,16:41
47070,540372,22553,PLASTERS IN TIN SKULLS,24,0.0,13081,United Kingdom,06/01/2011,16:41
56674,541109,22168,ORGANISER WOOD ANTIQUE WHITE,1,0.0,15107,United Kingdom,13/01/2011,15:10
86789,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,0.0,17560,United Kingdom,10/02/2011,13:08
130188,547417,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,0.0,13239,United Kingdom,23/03/2011,10:25
139453,548318,22055,MINI CAKE STAND HANGING STRAWBERY,5,0.0,13113,United Kingdom,30/03/2011,12:45
145208,548871,22162,HEART GARLAND RUSTIC PADDED,2,0.0,14410,United Kingdom,04/04/2011,14:42
157042,550188,22636,CHILDS BREAKFAST SET CIRCUS PARADE,1,0.0,12457,Switzerland,14/04/2011,18:57
187613,553000,47566,PARTY BUNTING,4,0.0,17667,United Kingdom,12/05/2011,15:21
198383,554037,22619,SET OF 6 SOLDIER SKITTLES,80,0.0,12415,Australia,20/05/2011,14:13
279324,561284,22167,OVAL WALL MIRROR DIAMANTE,1,0.0,16818,United Kingdom,26/07/2011,12:24
282912,561669,22960,JAM MAKING SET WITH JARS,11,0.0,12507,Spain,28/07/2011,17:09
285657,561916,M,Manual,1,0.0,15581,United Kingdom,01/08/2011,11:44
298054,562973,23157,SET OF 6 NATIVITY MAGNETS,240,0.0,14911,EIRE,11/08/2011,11:42
314745,564651,23270,SET OF 2 CERAMIC PAINTED HEARTS,96,0.0,14646,Netherlands,26/08/2011,14:19
314746,564651,23268,SET OF 2 CERAMIC CHRISTMAS REINDEER,192,0.0,14646,Netherlands,26/08/2011,14:19
314747,564651,22955,36 FOIL STAR CAKE CASES,144,0.0,14646,Netherlands,26/08/2011,14:19
314748,564651,21786,POLKADOT RAIN HAT,144,0.0,14646,Netherlands,26/08/2011,14:19
358655,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,0.0,16133,United Kingdom,25/09/2011,12:22
361825,568384,M,Manual,1,0.0,12748,United Kingdom,27/09/2011,09:46
379913,569716,22778,GLASS CLOCHE SMALL,2,0.0,15804,United Kingdom,06/10/2011,08:17
395529,571035,M,Manual,1,0.0,12446,RSA,13/10/2011,12:50
420404,572893,21208,PASTEL COLOUR HONEYCOMB FAN,5,0.0,18059,United Kingdom,26/10/2011,14:36
436428,574138,23234,BISCUIT TIN VINTAGE CHRISTMAS,216,0.0,12415,Australia,03/11/2011,11:26
436597,574175,22065,CHRISTMAS PUDDING TRINKET POT,12,0.0,14110,United Kingdom,03/11/2011,11:47
436961,574252,M,Manual,1,0.0,12437,France,03/11/2011,13:24
439361,574469,22385,JUMBO BAG SPACEBOY DESIGN,12,0.0,12431,Australia,04/11/2011,11:55
446125,574879,22625,RED KITCHEN SCALES,2,0.0,13014,United Kingdom,07/11/2011,13:22
446793,574920,22899,CHILDREN'S APRON DOLLY GIRL,1,0.0,13985,United Kingdom,07/11/2011,16:34
446794,574920,23480,MINI LIGHTS WOODLAND MUSHROOMS,1,0.0,13985,United Kingdom,07/11/2011,16:34
454463,575579,22437,SET OF 9 BLACK SKULL BALLOONS,20,0.0,13081,United Kingdom,10/11/2011,11:49
454464,575579,22089,PAPER BUNTING VINTAGE PAISLEY,24,0.0,13081,United Kingdom,10/11/2011,11:49
479079,577129,22464,HANGING METAL HEART LANTERN,4,0.0,15602,United Kingdom,17/11/2011,19:52
479546,577168,M,Manual,1,0.0,12603,Germany,18/11/2011,10:42
480649,577314,23407,SET OF 2 TRAYS HOME SWEET HOME,2,0.0,12444,Norway,18/11/2011,13:23
485985,577696,M,Manual,1,0.0,16406,United Kingdom,21/11/2011,11:57
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,0.0,13256,United Kingdom,25/11/2011,15:57

In [27]:
# remvoing zero or less than 0 in unit price
df = df[df["UnitPrice"]> 0]

In [28]:
#changing the type of customerID from integer to String
df["CustomerID"] = df["CustomerID"].astype("str")

In [29]:
#checking the summary statistics of the dataframe
df.describe()

            Quantity      UnitPrice
count  392692.000000  392692.000000
mean       13.119702       3.125914
std       180.492832      22.241836
min         1.000000       0.001000
25%         2.000000       1.250000
50%         6.000000       1.950000
75%        12.000000       3.750000
max     80995.000000    8142.750000

In [30]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Invoice_Day_Month_Year,Invoice_Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850,United Kingdom,01/12/2010,08:26
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850,United Kingdom,01/12/2010,08:26
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850,United Kingdom,01/12/2010,08:26
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850,United Kingdom,01/12/2010,08:26
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850,United Kingdom,01/12/2010,08:26

In [31]:
# creating revenue column for business analysis
df["Revenue"] = df["Quantity"] * df["UnitPrice"]
df.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Invoice_Day_Month_Year,Invoice_Time,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850,United Kingdom,01/12/2010,08:26,15.30
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850,United Kingdom,01/12/2010,08:26,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850,United Kingdom,01/12/2010,08:26,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850,United Kingdom,01/12/2010,08:26,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850,United Kingdom,01/12/2010,08:26,20.34

In [32]:
# checking the shape of updated dataframe
df.shape

(392692, 10)

In [33]:
# checking the datatypes of the updated dataframe
df.dtypes

InvoiceNo                     str
StockCode                     str
Description                   str
Quantity                    int64
UnitPrice                 float64
CustomerID                    str
Country                       str
Invoice_Day_Month_Year        str
Invoice_Time                  str
Revenue                   float64
dtype: object

In [34]:
#renaming the dataframe columns for importing it in postgreSQL
df = df.rename(columns={
    "InvoiceNo": "invoice_no",
    "StockCode": "stock_code",
    "Description": "description",
    "Quantity": "quantity",
    "UnitPrice": "unit_price",
    "CustomerID": "customer_id",
    "Country": "country",
    "Invoice_Day_Month_Year": "invoice_day_month_year",
    "Invoice_Time": "invoice_time",
    "Revenue":"revenue"
})

In [35]:
# checking the renamed columns
df.columns

Index(['invoice_no', 'stock_code', 'description', 'quantity', 'unit_price',
       'customer_id', 'country', 'invoice_day_month_year', 'invoice_time',
       'revenue'],
      dtype='str')

In [36]:
# saving the new cleaned csv for postgresql
df1 = pd.read_csv("cleaned_ecommerce.csv")

# 2. Loading Data into PostgreSQL

After cleaning, the dataset was loaded into PostgreSQL.

PostgreSQL was used for:

- Business queries
- Customer analysis
- Sales analysis
- Aggregations
- Creating views for visualization

The cleaned dataframe was stored as the `sales` table.

In [37]:
# connecting to postgreSQL for business analysis
from sqlalchemy import create_engine

username = "postgres"
password = "benedetta"
host = "localhost"
port = "5433"
database = "ecommerce"

engine_url = f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
engine = create_engine(engine_url)

#Loading dataframe into PostgreSql
table_name = "sales"
table_name1 = "original_sales"
df_org.to_sql(table_name1, engine, if_exists="replace", index=False)

from sqlalchemy import text
with engine.connect() as conn:
    conn.execute(
        text("""
    DROP VIEW IF EXISTS
    kpi_summary,
    monthly_revenue,
    monthly_orders,
    top_products_revenue,
    top_products_quantity,
    top_customers,
    rfm_segments,
    customer_retention,
    country_revenue,
    country_orders,
    product_pareto
    CASCADE;
    """)
    )
    conn.commit()
df1.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded to {table_name1} in database: {database}")
print(f"Data successfully loaded to {table_name} in database: {database}")

Data successfully loaded to original_sales in database: ecommerce
Data successfully loaded to sales in database: ecommerce